artizan-db:
  image: mariadb
  ports:
    - "8081:3306"
  environment:
    MYSQL_ROOT_PASSWORD: jamer

artizan-wp:
  image: wordpress
  volumes:
    - ./:/var/www/html
  ports:
    - "8080:80"
  links:
    - artizan-db:mysql
  environment:
    WORDPRESS_DB_PASSWORD: jamer